apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: webserver
data:
  index.html: |
    <!DOCTYPE html>
    <html>
      <head>
      </head>
      <body>
      <h1>This is a test!</h1>
      </body>
    </html>
